name: dissimilar_tasks
classname: salina_cl.scenarios.BraxScenario
domain: halfcheetah
tasks: ["carry_stuff_hugegravity","moon","defective_module","hugefoot_rainfall","normal","tinyfoot","hugefoot","carry_stuff","tinyfoot_moon","rainfall"]
repeat_scenario: 1
n_train_envs: 128
n_evaluation_envs: 512
n_steps: 1_000_000