name: random_tasks
classname: salina_cl.scenarios.BraxScenario
domain: halfcheetah
tasks: ['tinyfoot','normal','hugefoot_rainfall','moon','defective_module','carry_stuff_hugegravity','rainfall','hugefoot','tinyfoot_moon','carry_stuff']
repeat_scenario: 1
n_train_envs: 128
n_evaluation_envs: 512
n_steps: 1_000_000