name: normal
classname: salina_cl.scenarios.BraxScenario
domain: halfcheetah
tasks: ["normal","moon","tinyfoot","rainfall"]
repeat_scenario: 1
n_train_envs: 128
n_evaluation_envs: 512
n_steps: 1_000_000