logger:
  classname: salina.logger.TFLogger
  log_dir: ./bc
  modulo: 1
  every_n_seconds: 10
  verbose: True

n_envs: 1
env_name: hopper-medium-replay-v2

#env_name: antmaze-medium-diverse-v0
embedding_size: 128
env:
  classname: salina_examples.offline_rl.d4rl.make_d4rl_env
  env_name: ${env_name}
  max_episode_steps: 1000

agent:
  classname: salina_examples.offline_rl.decision_transformer.agents.ActionMLPAgentFromObservation
  env: ${env}
  n_layers: 2
  hidden_size: 128
  embedding_size: ${embedding_size}
  maximum_episode_steps: 1000
  use_timestep: True
  use_reward_to_go: True

algorithm:
  env_seed: 432
  batch_size: 32
  max_epoch: 10000000
  clip_grad: 2
  optimizer:
    classname: torch.optim.Adam
    lr: 0.001
  reward_scale: 1000.0
  target_rewards:
    - 4000
    - 3600
    - 2500
    - 1800
    - 0
  loss_device: cpu

  evaluation:
    env_seed: 23
    n_envs: 64
    n_processes: 4
