name: ewc
seed: 0

defaults: 
  - logger: wandb
  - scenario: halfcheetah/forgetting
  - hydra: hydra
  - framework/params/algorithm/generic_sac
  - framework/params/policy_agent/generic_policy
  - framework/params/critic_agent/generic_critic
  - framework/params/evaluation/generic_evaluation
  - optional framework/params/evaluation: ${scenario}
  - optional framework/params/algorithm: ${scenario} # best HPS for sac are loaded if available
  - optional framework/params/policy_agent: ${scenario} # using layer norm and random policy warmup if CW
  - optional framework/params/critic_agent: ${scenario} # using layer norm if CW

frameowkr:
  classname: salina_cl.frameworks.TwoSteps
  seed: ${seed}
  params:
    checkpoint: False

    algorithm2:
      classname: salina_cl.algorithms.EWC
      params:
        device: cuda:0
        n_samples: 1024
        
    policy_agent:
      classname: salina_cl.agents.EWCActionAgent
      fisher_coeff: 1. # 0.01,1.,100.,10000.