name: cw10
classname: scenarios.CWScenario
domain: continual_world
tasks: [
  "hammer-v2",
  "push-wall-v2",
  "faucet-close-v2",
  "push-back-v2",
  "stick-pull-v2",
  "handle-press-side-v2",
  "push-v2",
  "shelf-place-v2",
  "window-close-v2",
  "peg-unplug-side-v2",
]
repeat_scenario: 1
n_train_envs: 1
n_evaluation_envs: 1
n_steps: 1_000_000
start_steps: 1_000
evaluate_success: True
